INSERT INTO `recetas` (`id`, `nombre`,`nacionalidad`, `ingredientes`, `explicacion`, `tiempo`) VALUES
(1, 'Tortilla de patata', 'Española', '5 huevos, 500 g patatas, 1 cebolla, sal y aceite de oliva', 'Pelamos y lavamos las patatas, las cortamos en rodajas finas al igual que la cebolla. Ponemos ambas cosas en una sartén y cubrimos de aceite de oliva virgen extra, dejamos que se hagan a fuego medio-suave hasta que comiencen a dorarse. Sabréis que las patatas están hechas cuando comiencen a romperse, con la paleta. Para que la tortilla esté jugosa es importante que las patatas se hagan bien y se confiten, porque no hay nada peor que una tortilla con las patatas medio crudas. Por lo tanto, paciencia con este paso.
Las sacamos de la sartén y escurrimos bien. Ponemos en un cuenco grande, aparte batimos los huevos y los añadimos a las patatas y a la cebolla, añadimos un poco de sal y mezclamos. Dejamos un par de minutos que se mezclen bien. Aquí hay quien prefiere dejar las patatas enteras y quien prefiere machacarlas un poco con la paleta para que se mezclen bien con el huevo.
Ponemos en la sartén un par de cucharadas de aceite de oliva virgen extra y vertemos todo. Al principio rompemos un poco, como si fuéramos a hacer un revuelto, luego vamos dándole forma  por los bordes. Cuando veamos que ya está cuajada por abajo ponemos un plato o una tapa encima de la sartén y le damos la vuelta rápidamente. Ponemos de nuevo la sartén en el fuego y deslizamos la tortilla desde el plato a la sartén. Dejamos unos minutos más (2 o 3 si te gusta más cuajada, menos si te gusta jugosa) para que se termine de hacer y ya tenemos lista nuestra tortilla de patatas.', '45 minutos'),
(2, 'Gazpacho', 'Española', '1 kg de tomates maduros, 1 pimiento verde, 1 pepino, 1 cebolleta, 1 diente de ajo, 1 rebanada de pan, 1 cucharadita de sal, 2 cucharadas de vinagre, 3 cucharadas de aceite de oliva', 'Lavamos muy bien los tomates y el pimiento ya que los vamos a triturar con piel. Ponemos en el vaso de la batidora o si tenéis un robot de cocina o vaso americano, el pimiento troceado, el tomate troceado, el pepino pelado y troceado, el pan y la cebolleta pelada y en cuartos. Añadimos la sal y el vinagre, trituramos todo durante varios minutos hasta obtener una crema muy fina.
Añadimos un poco de aceite de oliva virgen extra y mezclamos de nuevo. En este momento lo podéis servir así o si lo queréis más líquido, añadid agua y mezclad todo de nuevo. Ya sólo queda meterlo en el frigorífico y dejar que se enfríe. Mezclar de nuevo a la hora de servir.', '15 minutos'),
(3, 'Salmorejo cordobés','Española', '1 kg de tomates maduros, 200 gr de pan, 150 ml de aceite de oliva,1 diente de ajo y  sal al gusto', 'Para hacer el salmorejo, me gusta ir mezclando los ingredientes paso a paso para así conseguir la textura perfecta. Comienzo lavando los tomates, retirando lo verde del pedúnculo y triturándolos. No es necesario pelar ni quitar las pepitas porque después paso el puré de tomate por un colador fino donde se queda todo pasando solamente el tomate.
En un bol coloco el pan y lo cubro con el puré de tomate dejando que se impregne durante unos diez minutos. Pasado ese tiempo, incorporo el diente de ajo y trituro bien con la batidora o con la Thermomix y obtengo una crema espesa de pan y tomate. La proporción de pan que yo uso es estupenda para esta textura, pero podéis variarla en función del agua que tengan los tomates que utilicéis y de lo consistente que sea la miga.
A continuación incorporo el aceite de oliva virgen extra. Un buen salmorejo se debería hacer siempre con aceite de la zona de Córdoba, por lo que si podéis, cualquier variedad de la D.O. Priego de Córdoba es la idónea, pero en todo caso, si no tenéis de allí, utilizad un buen aceite de oliva virgen extra que conseguirá la emulsión perfecta y un resultado cremoso y espeso.
Tras echar el aceite volvemos a turbinar todo en el robot de cocina o a base de batidora y paciencia hasta que nuestro salmorejo sea uniforme, con un bonito color anaranjado y suficientemente compacto como para aguantar sobre su superficie los tradicionales tropezones de guarnición con los que se decora cada ración.', '15 minutos'),
(4, 'Migas de pastor','Española', '500 gr de pan duro, 300 ml de agua, 1 cucharadita de sal , 2-3 chorizos frescos, 2 pimientos verdes, 3 tiras de panceta, 6 dientes de ajo y 100 ml de aceite de oliva', 'Empezamos desmigando el pan. Para ello, lo más sencillo es utilizar un batidor de vaso, robot de cocina o similar y triturar el pan en 3 tandas. La idea es que quede desmigado pero no en exceso, con pocos trozos grandes, como puedes ver en la fotografía. Si lo trituras así, primero córtalo en rodas y después cada rodaja en 2 o 3 trozos, pero si no tienes estas herramientas también puedes utilizar un cuchillo.
Pon el agua en un recipiente y echa en él la sal, removiendo para que se disuelva un poco. Vierte el agua sobre el pan y mezcla un poco. Deja reposar 1 hora para que el pan se humedezca.
Corta los chorizos en rodajas.
Pon una sartén antiadherente a fuego medio (lo suficientemente grande como para que después te quepa toda la masa de las migas, no como yo que me equivoqué y empecé utilizando una pequeña) y cuando esté caliente echa el chorizo y cocínalo un par de minutos por cada lado o hasta que se dore un poco.
Retira el chorizo a un plato aparte y con la grasa, personalmente lo que hago es en gran parte empaparla con papel de cocina porque suele soltar mucha. Puedes utilizarla si lo prefieres, pero a mi me empacha un poco tanta grasa del chorizo.
Quítale al tocino la piel y córtalo en tiras.
Echa los 100 ml de aceite de oliva a la sartén y cuando esté caliente fríe el tocino con un poco de sal hasta que esté dorado a tu gusto, tardará unos 5 minutos. Ve removiéndolo de vez en cuando y retíralo cuando esté a tu gusto, siempre procurando que el aceite se quede en la sartén.
Lava el pimiento verde, retírale el rabo y las semillas del interior y córtalo en trozos o en rodajas.
Fríe el pimiento verde y los ajos (con piel) en el aceite que ha dejado el tocino durante unos 5 minutos o hasta que esté dorado. Reserva aparte los pimientos pero los ajos déjalos en la sartén.
Echa a la sartén las migas remojadas y cocínalas hasta que estén listas (pueden tardar entre 20 y 30 minutos), removiendo cada poco tiempo. Estarán listas cuando estén a tu gusto, idealmente doraditas y un poco sueltas.
Añade el resto de ingredientes a la sartén: el chorizo, el tocino y el pimiento verde. Cocínalo todo junto durante un par de minutos y ya están listas.', '1hora'),
(5, 'Masa de pizza','Italiana', '500 gr de harina de fuerza, 18 gr de levadura fresca, 4 cucharadas soperas de aceite de oliva, 1 cucharadita de sal y  250 ml de agua tibia', 'Pon el agua templada en un vaso, desmenuza la levadura y añádela al agua. Remueve muy bien hasta que quede disuelta. Pon la harina en un bol amplio con la cucharadita de sal, mezcla. Haz un hueco en el medio de la harina y, en él, añade el aceite y la mezcla de la levadura.
Remueve todo y mezcla, ve amasando hasta que queden todos los ingredientes integrados en forma de masa. Saca la masa a la encimera (previamente enharinada) y continúa amasando durante 8-10 minutos. Ha de quedar una masa compacta y que ya no se pegue en las manos.
Forma una bola con la masa de pizza y déjala reposar unos 45 minutos o una hora, tapada con un paño.
Cuando haya pasado el tiempo, retira el paño. Verás que la masa de pizza fácil habrá duplicado su volumen.
Saca la masa de pizza casera del bol y amásala unos minutos dobándola en sí misma haciendo pliegues con ella.
Con esta cantidad de masa, tendrás para preparar dos pizzas caseras. Córtala por la mitad, coge una de las mitades y amásala. Ve estirando la masa de la pizza italiana en la encimera hasta dejarla del grosor que te guste. Hornéala con el horno precalentado al máximo durante unos 6-15 minutos (o hasta que esté dorada). Sácala y añade los ingredientes para que puedas terminar de hornearla. ', '1 hora y 30 minutos'),
(6, 'Finibus Bonorum ','Italiana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(7, 'ebitis aut rer ','Italiana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(8, 'delectus, ut ','Italiana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(9, 's doloribu ','Venezolana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(10, 'accusamus et iusto','Venezolana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(11, 'laborum et dolorum ','Venezolana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente'),
(12, 'um quid ','Venezolana', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
', 'tenetur a sapiente');










